SECDIR review
core-wg/oscore-edhoc pull request #18
Opened 2023-11-17 18:30 UTC by marco-tiloca-sics

This PR addresses the SECDIR review archived at https://mailarchive.ietf.org/arch/msg/secdir/6xBm7c_0kCzNtV16DM9vXuV3RF4/

2023-11-20 17:40 UTC, cabo requested changes
Assuming the changes that already were in 15-17 are the same.

Unaddressed:
"sum of the MACs" -> sum of the strengths...
(really: combining the strengths, because separate MACs can be attacked separately in general)

2023-11-20 17:40 UTC, cabo commented on draft-ietf-core-oscore-edhoc.md
> +The performance advantage of using the EDHOC + OSCORE request can be lost when used in combination with Block-wise transfers that rely on specific parameter values and block sizes. Application polici
Unneeded "such"
Typo

```suggestion
The performance advantage of using the EDHOC + OSCORE request can be lost when used in combination with Block-wise transfers that rely on specific parameter values and block sizes. Application policies at the CoAP client can define when and how to detect whether the performance advantage is lost, and, if that is the case, whether to appropriately adjust the parameter values and block sizes, or instead to fall back on the sequential workflow of EDHOC. Further considerations on this topic are out of the scope of this document.
```

2023-11-20 17:40 UTC, cabo commented on draft-ietf-core-oscore-edhoc.md
> +The performance advantage of using the EDHOC + OSCORE request can be lost when used in combination with Block-wise transfers that rely on specific parameter values and block sizes. Application polici
I'm not a big fan of the last new sentence.
Can we point to implem-cons already?
Then we could make this a simple reference, as in "Further implementation considerations on this topic can be found in..."

2023-11-21 08:59 UTC, marco-tiloca-sics commented
> Assuming the changes that already were in 15-17 are the same.
> 
> Unaddressed: "sum of the MACs" -> sum of the strengths... (really: combining the strengths, because separate MACs can be attacked separately in general)

Now changed in https://github.com/core-wg/oscore-edhoc/pull/18/commits/71c456f34fbaa8834eb83489284946af055ca24e

2023-11-22 08:35 UTC, marco-tiloca-sics commented
> Assuming the changes that already were in 15-17 are the same.
> 
> Unaddressed: "sum of the MACs" -> sum of the strengths... (really: combining the strengths, because separate MACs can be attacked separately in general)

Now further addressed in https://github.com/core-wg/oscore-edhoc/pull/18/commits/e859cacf036443186fd9b7c8499f1ad6a383304d

2023-11-22 09:39 UTC, cabo approved these changes
Thank you for addressing my concerns!

I have one more editorial proposal (see two suggestions below).

2023-11-22 09:39 UTC, cabo commented on draft-ietf-core-oscore-edhoc.md
> +* The Initiator is authenticated with 128-bit security against online attacks. Consistent with {{Section 9.1 of I-D.ietf-lake-edhoc}}, this results from the combination of the strength of the 64-bit
I'd probably use "as per", to identify this as essentially a restatement.
Not quite sure how this is free-standing, as "consistent with" would imply.

```suggestion
* The Initiator is authenticated with 128-bit security against online attacks. As per {{Section 9.1 of I-D.ietf-lake-edhoc}}, this results from the combination of the strength of the 64-bit MAC in EDHOC message_3 and of the 64-bit MAC in the AEAD of the first OSCORE-protected CoAP request, as rebuilt at step 7 of {{server-processing}}.
```

2023-11-22 09:39 UTC, cabo commented on draft-ietf-core-oscore-edhoc.md
> +* The Responder is authenticated with 128-bit security against online attacks. Consistent with {{Section 9.1 of I-D.ietf-lake-edhoc}}, this results from the combination of the strength of the 64-bit
Ditto:

```suggestion
* The Responder is authenticated with 128-bit security against online attacks. As per {{Section 9.1 of I-D.ietf-lake-edhoc}}, this results from the combination of the strength of the 64-bit MAC in EDHOC message_2 and of the 64-bit MAC in the AEAD of the first OSCORE-protected CoAP response.
```

2023-11-23 08:16 UTC, rikard-sics approved these changes
LGTM

2023-11-29 12:34 UTC, gselander commented
Hearing no objection I now merge this.

2023-11-29 12:34 UTC, merged